DROP SCHEMA IF EXISTS `TOMORROWS_DB`; 

CREATE SCHEMA `TOMORROWS_DB`;

USE `TOMORROWS_DB`;

CREATE TABLE CLIENTE 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,   
 EMAIL VARCHAR(60),  
 CNPJ VARCHAR(14) NOT NULL,  
 RAZAO_SOCIAL VARCHAR(150) NOT NULL, 
 NOME_FANTASIA VARCHAR(150),
 LOGRADOURO VARCHAR(150),  
 BAIRRO VARCHAR(50),  
 COMPLEMENTO VARCHAR(100), 
 NUMERO INT,
 CIDADE VARCHAR(100) NOT NULL,
 END_INFORMADO VARCHAR(1) NOT NULL,
 TIPO_CLIENTE ENUM('E','F','J') NOT NULL,
 INSC_ESTADUAL VARCHAR(15),
 UNIQUE (CNPJ, INSC_ESTADUAL)
); 

CREATE TABLE PRESTADOR 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,    
 CNPJ VARCHAR(14) NOT NULL,  
 CIDADE VARCHAR(100) NOT NULL,
 UNIQUE (CNPJ)
); 

CREATE TABLE SERVICO 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,   
 DESCRICAO VARCHAR(250),  
 CODIGO VARCHAR(5),  
 ALIQUOTA FLOAT(4,2),  
 SITUACAO_TRIBUTARIA SMALLINT UNSIGNED,  
 LOCAL_PRESTACAO VARCHAR(100),  
 TRIBUTACAO_MUNICIPAL ENUM('S','N'),
 VALOR_UNITARIO FLOAT(8,2)
); 

CREATE TABLE ITEM_SERVICO 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 QUANTIDADE INT,  
 IDNOTA INT UNSIGNED,
 IDSERVICO INT UNSIGNED
); 

CREATE TABLE NOTA 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,    
 VALOR_TOTAL FLOAT(11,2),  
 STATUS_NOTA VARCHAR(50),  
 CHAVE_IDENTIFICADOR VARCHAR(50),  
 DATA_EMISSAO DATE,
 IDCLIENTE INT UNSIGNED,  
 IDPRESTADOR INT UNSIGNED 
); 

ALTER TABLE ITEM_SERVICO ADD FOREIGN KEY(IDSERVICO) REFERENCES SERVICO (ID);
ALTER TABLE ITEM_SERVICO ADD FOREIGN KEY(IDNOTA) REFERENCES NOTA (ID);
ALTER TABLE NOTA ADD FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE NOTA ADD FOREIGN KEY(IDPRESTADOR) REFERENCES PRESTADOR (ID);

INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '80680093000181', 'Junior Sistemas ME', 'Junior Sistemas', 'R. Rio de Janeiro', 'Konder Victor', '', '1318', '8147', '1', 'J', '');
INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '04475530000147', 'Empresa Desmonstracao Ltda', '','Avenida 7 de Setembro', 'Centro', 'Sala 01', '966', '8117', '1', 'J', '');
INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '00000000000191', 'Empresa Cliente Ltda', '', 'Rua da Capivara', 'Capivarianos', 'Terreo', '123','8055', '1', 'J', '');

INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '25825307000152', '8357');
INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '12345678901235', 'Cidade');
INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '12345678901236', 'Cidade');

INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '350.00', 'Status', 'Chave Indentificador', NOW(),'1', '1');
INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '400.00', 'Status', 'Chave Indentificador', NOW(),'2', '1');
INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '1500.00', 'Status', 'Chave Indentificador', NOW(),'3', '1');

INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Execucao, por administracao, empreitada ou subempreitada, de obras de construcao civil, hidraulica ou elétrica e de outras obras semelhantes.', '702', '5.00', '0', '8357', 'S', '35.00');
INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Instalacao e montagem de aparelhos, maquinas e equipamentos, inclusive montagem industrial, prestados ao usuario final, exclusivamente com material por ele fornecido.', '1406', '3.00', '0', '8357', 'S', '20.00');
INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Franquia (franchising)', '1708', '2.00', '0', '8357', 'S', '50.00');

INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '10', '1', '1');
INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '20', '2', '2');
INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '30', '3', '3');