DROP SCHEMA IF EXISTS `TOMORROWS_DB`; 

CREATE SCHEMA `TOMORROWS_DB`;

USE `TOMORROWS_DB`;

CREATE TABLE CLIENTE 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,   
 EMAIL VARCHAR(60),  
 CNPJ VARCHAR(14) NOT NULL,  
 RAZAO_SOCIAL VARCHAR(150) NOT NULL, 
 NOME_FANTASIA VARCHAR(150),
 LOGRADOURO VARCHAR(150),  
 BAIRRO VARCHAR(50),  
 COMPLEMENTO VARCHAR(100), 
 NUMERO INT,
 CIDADE VARCHAR(100) NOT NULL,
 END_INFORMADO VARCHAR(1) NOT NULL,
 TIPO_CLIENTE ENUM('E','F','J') NOT NULL,
 INSC_ESTADUAL VARCHAR(15),
 UNIQUE (CNPJ, INSC_ESTADUAL)
); 

CREATE TABLE PRESTADOR 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,    
 CNPJ VARCHAR(14) NOT NULL,  
 CIDADE VARCHAR(100) NOT NULL,
 UNIQUE (CNPJ)
); 

CREATE TABLE SERVICO 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,   
 DESCRICAO VARCHAR(250),  
 CODIGO VARCHAR(5),  
 ALIQUOTA FLOAT(4,2),  
 SITUACAO_TRIBUTARIA SMALLINT UNSIGNED,  
 LOCAL_PRESTACAO VARCHAR(100),  
 TRIBUTACAO_MUNICIPAL ENUM('S','N'),
 VALOR_UNITARIO FLOAT(8,2)
); 

CREATE TABLE ITEM_SERVICO 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 QUANTIDADE INT,  
 IDNOTA INT UNSIGNED,
 IDSERVICO INT UNSIGNED
); 

CREATE TABLE NOTA 
( 
 ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,    
 VALOR_TOTAL FLOAT(11,2),  
 STATUS_NOTA VARCHAR(50),  
 CHAVE_IDENTIFICADOR VARCHAR(50),  
 DATA_EMISSAO DATE,
 IDCLIENTE INT UNSIGNED,  
 IDPRESTADOR INT UNSIGNED 
); 

ALTER TABLE ITEM_SERVICO ADD FOREIGN KEY(IDSERVICO) REFERENCES SERVICO (ID);
ALTER TABLE ITEM_SERVICO ADD FOREIGN KEY(IDNOTA) REFERENCES NOTA (ID);
ALTER TABLE NOTA ADD FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE NOTA ADD FOREIGN KEY(IDPRESTADOR) REFERENCES PRESTADOR (ID);

INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '12345678901234', 'Razão', 'Nome Fantasia', 'Logradouro', 'Bairro', 'Complemento', '123','Cidade', '1', 'J', 'Incrição');
INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '12345678901235', 'Razão', 'Nome Fantasia','Logradouro', 'Bairro', 'Complemento', '123','Cidade', '1', 'J', 'Incrição');
INSERT INTO `TOMORROWS_DB`.`CLIENTE` VALUES (DEFAULT, 'cliente@teste.com', '12345678901236', 'Razão', 'Nome Fantasia','Logradouro', 'Bairro', 'Complemento', '123','Cidade', '1', 'J', 'Incrição');

INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '12345678901234', 'Cidade');
INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '12345678901235', 'Cidade');
INSERT INTO `TOMORROWS_DB`.`PRESTADOR` VALUES (DEFAULT, '12345678901236', 'Cidade');

INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '11.2', 'Status', 'Chave Indentificador', NOW(),'1', '1');
INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '11.2', 'Status', 'Chave Indentificador', NOW(),'2', '2');
INSERT INTO `TOMORROWS_DB`.`NOTA` VALUES (DEFAULT, '11.2', 'Status', 'Chave Indentificador', NOW(),'3', '3');

INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Descrição', 'Cod', '4.2', '1', 'Local', 'S', '8.2');
INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Descrição', 'Cod', '4.2', '1', 'Local', 'S', '8.2');
INSERT INTO `TOMORROWS_DB`.`SERVICO` VALUES (DEFAULT, 'Descrição', 'Cod', '4.2', '1', 'Local', 'S', '8.2');

INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '10', '1', '1');
INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '20', '2', '2');
INSERT INTO `TOMORROWS_DB`.`ITEM_SERVICO` VALUES (DEFAULT, '30', '3', '3');